version: '3.7'

services:
  spark-master:
    container_name: spark-master
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: "6g"
    build:
      context: ./spark/master
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
      - "7077:7077"
      - "18080:18080"
      - "22:22"
      - "5050:8080"
    volumes:
      - ./submitfiles:/opt/submitfiles
    networks:
      dahbest:
        aliases:
          - spark-master
        ipv4_address: 172.80.0.110

  spark-worker-1:
    container_name: spark-worker-1
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: "7g"
    build:
      context: ./spark/worker
      dockerfile: Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8081-8089:8081"
    volumes:
      - ./submitfiles:/opt/submitFiles
    networks:
      dahbest:
        aliases:
          - spark-worker-1
        ipv4_address: 172.80.0.111

  spark-worker-2:
    container_name: spark-worker-2
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: "7g"
    build:
      context: ./spark/worker
      dockerfile: Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8081-8089:8081"
    volumes:
      - ./submitfiles:/opt/submitFiles
    networks:
      dahbest:
        aliases:
          - spark-worker-2
        ipv4_address: 172.80.0.112
        
volumes:
  submitfiles:
  
networks:
  dahbest:
    name: dahbest
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
    
